name: echo-discord-bot

services:
  bot:
    container_name: echo-discord-bot
    image: delemangi/echo-discord-bot:latest
    restart: unless-stopped
    environment:
      TOKEN: ${TOKEN}
      APPLICATION_ID: ${APPLICATION_ID}
      STRAPI_URL: ${STRAPI_URL}
    depends_on:
      - strapi

  strapi:
    container_name: echo-strapi
    image: delemangi/echo-strapi:latest
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: database
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      HOST: ${HOST}
      PORT: ${PORT}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./public/uploads:/opt/app/public/uploads
    depends_on:
      - database

  database:
    container_name: echo-postgres
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data/
