name: echo-discord-bot-dev

services:
  bot:
    container_name: echo-discord-bot-dev
    image: echo-discord-bot-dev:latest
    build:
      context: ./bot
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - database

  database:
    container_name: echo-strapi-dev
    image: echo-strapi-dev:latest
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./db/.tmp:/opt/app/.tmp
      - ./db/database:/opt/app/database
