FROM node:20-alpine
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev
ENV NODE_ENV=development

WORKDIR /opt/
COPY package.json package-lock.json ./
RUN npm i -g node-gyp
RUN npm config set fetch-retry-maxtimeout 600000 -g && npm i
ENV PATH /opt/node_modules/.bin:$PATH

WORKDIR /opt/app
COPY . .

RUN chown -R node:node /opt/app
USER node

RUN npm run build

CMD ["npm", "run", "develop"]
